# Generated by Django 5.2.3 on 2025-07-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.TextField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='flori/')),
                ('stoc', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
